### ISSUE TITLE
README.md's tarball URL is wrong. it doesn't exist.

### ISSUE THREAD

**Issue by saeho** [iHealthLab/test-labs#3]
In readme, it says to add:
cordova:com.ihealth.plugin.bpmanagercordova@https://github.com/iHealthLab/labs/tree/master/cordovaPluginForBp/tarball/bdaeac2cd9154dfe08911e88bf6c7e199fe0f28b

That tarball URL doesn't exist. The actual App uses:
https://github.com/iHealthLab/labs/tree/master/cordovaPluginForBp/tarball/bdaeac2cd9154dfe08911e88bf6c7e199fe0f28b

**Comment by saeho** [comment]
sorry i meant https://github.com/iHealthLab/plugin-ihealth-bp/tarball/33951e800d372ce9a244ec62dde4529315cb24f7

**Comment by ihealthdavid** [comment]
Please use get the full SHA from the commit page:
https://github.com/iHealthLab/test-labs/commits/master
